development:
  adapter: postgresql
  encoding: utf8
  database: mailcheck_development
  host: localhost
  pool: 5
  username: sairails
  password: randomwalk893

test:
  adapter: postgresql
  encoding: utf8
  database: mailcheck_test
  host: localhost
  pool: 5
  username: sairails
  password: randomwalk893

production:
  adapter: postgresql
  encoding: utf8
  database: 
  pool: 5
  username: 
  password: 