development:
  adapter: postgresql
  encoding: utf8
  database: dailycheck1_development
  host: localhost
  pool: 5
  username: dailycheck1
  password: prashanth320

test:
  adapter: postgresql
  encoding: utf8
  database: dailycheck_test
  host: localhost
  pool: 5
  username: dailycheck1
  password: prashanth320

production:
  adapter: postgresql
  encoding: utf8
  database: 
  pool: 5
  username: 
  password: 